name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build json-diff-viewer
        run: |
          cd json-diff-viewer
          npm install --include=dev
          npm run build

      - name: Prepare publish directory
        run: |
          mkdir -p publish/json-diff-viewer
          cp -r json-diff-viewer/build/* publish/json-diff-viewer/
          cp docs/index.html publish/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
