name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Downgrade npm (react-scripts 5 compatibility)
        run: npm install -g npm@9

      - name: Build json-diff-viewer
        run: |
          cd json-diff-viewer
          npm install --legacy-peer-deps
          npm run build

      - name: Prepare publish directory
        run: |
          rm -rf publish
          mkdir -p publish
          mv json-diff-viewer/build publish/json-diff-viewer
          cp docs/index.html publish/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish

